window.onload=function(){var a={};$.ajax({type:"GET",url:"/core/os/default/System.json",success:function(d){a.system=d;program(a)}})};var System,Defaults,windows;
function program(a){function d(){g.clear();g.fillStyle=System.osDesktopBackground;g.fillRect(0,0,e.width,e.height);for(var b=0;b<windows.length;b++){var a=windows[b];if(a.shown){g.fillStyle=System.osWindowOptionsBackground;g.fillRect(a.x,a.y,a.width,System.osWindowOptionsHeight);g.fillStyle=a.gdata.bg;g.fillRect(a.x,a.y+System.osWindowOptionsHeight,a.width,a.height-System.osWindowOptionsHeight);try{g.drawImage(a.icon,a.x+System.osWindowOptionsPadding,a.y+System.osWindowOptionsHeight/2-System.osWindowIconHeight/
2,System.osWindowIconWidth,System.osWindowIconHeight)}catch(B){a.icon=Image.getIcon(System.osApplicationIcon)}var d=document.createElement("canvas");d.width=a.width;d.height=a.height;var w=d.getContext("2d");w.font=System.osWindowContentFont;w.textBaseline="middle";w.fillStyle=System.osWindowOptionsColor;w.fillText(a.title,System.osWindowOptionsPadding+System.osWindowIconWidth+System.osWindowOptionsTitleIconSeperation,System.osWindowOptionsHeight/2);w.textBaseline="top";var c=document.createElement("canvas");
c.width=a.width;c.height=a.height-System.osWindowOptionsHeight;for(var f=c.getContext("2d"),h=0;h<a.gdata.elements.length;h++){var k=a.gdata.elements[h],l=k.data;if(defined(l.fc))switch(f.fillStyle=l.fc,k.type){case r.SQUARE:f.fillRect(l.x,l.y,l.w,l.h);break;case r.ELLIPSE:f.fillEllipse(l.x,l.y,l.w,l.h)}if(defined(l.sc))switch(f.strokeStyle=l.sc,k.type){case r.SQUARE:f.strokeRect(l.x,l.y,l.w,l.h);break;case r.ELLIPSE:f.strokeEllipse(l.x,l.y,l.w,l.h)}}w.drawImage(c,0,System.osWindowOptionsHeight);
g.drawImage(d,a.x,a.y);g.strokeStyle=System.osWindowBorder;g.lineWidth=System.osWindowBorderWidth;g.strokeRect(a.x,a.y,a.width,a.height);g.strokeStyle=System.osWindowOptionsBorder;g.lineWidth=System.osWindowOptionsBorderWidth;g.beginPath();g.moveTo(a.x,a.y+System.osWindowOptionsHeight);g.lineTo(a.x+a.width,a.y+System.osWindowOptionsHeight);g.stroke()}}}var e=document.getElementById("desktop");e.width=window.innerWidth;e.height=window.innerHeight;var m=e.getContext("2d");System=a.system;Defaults={windowGData:{bg:System.osWindowContentBackground,
elements:[]}};var r={SQUARE:0,ELLIPSE:1};setInterval(d,20);var g=m,x=(new Date).getTime();windows=[];new Application({commands:[{action:"compile",source:"/core/os/default/apps/test.js",dest:"/apps/test.ose",callback:function(b){console.log("Application compiled sucessfully in "+((new Date).getTime()-x).toString()+" milliseconds!");console.log("Result:\n"+b)}},{action:"execute",source:"/apps/test.ose"}]});new Window(10,10,200,100,"Test");new Window(100,100,200,100,"Test2");windows[windows.length-1].addEventListener("mousedown",
function(b){console.log("X: "+b.x+", Y: "+b.y)});a=new Worker("text.js");a.postMessage({action:"data",value:System});a.postMessage({action:"widthIndex",value:JSON.stringify(getWidthIndex(System.osWindowContentFont))});var z=0,A=0,t=null,y=!1,q=8,h=null,u,v,n,p;window.onmousedown=function(b){var a="";t=null;y=!0;for(var d=[],e=0;e<windows.length;e++)b.x>windows[e].x&&b.x<windows[e].x+windows[e].width&&b.y>windows[e].y&&b.y<windows[e].y+windows[e].height&&d.push(e);d.pop();for(e=windows.length-1;0<=
e;e--){var c=windows[e],f=System.osWindowResizeMargin;if(b.x>=c.x&&b.y>=c.y&&b.x<=c.x+c.width&&b.y<=c.y+c.height){if(b.x>=c.x+f&&b.y>=c.y+f&&b.x<=c.x+c.width-f&&b.y<=c.y+c.height-f)a="window",b.y<c.y+System.osWindowOptionsHeight&&(t=c,z=b.x-c.x,A=b.y-c.y);else break;if(-1==d.indexOf(e)){windows=windows.remove(e);windows.push(c);d=windows[windows.length-1];b.y>d.y+System.osWindowOptionsHeight&&d.event.mousedown({x:b.x-d.x,y:b.y-d.y-System.osWindowOptionsHeight});break}if(e==windows.length-1)break}}if(""==
a)for(e=windows.length-1;0<=e;e--)c=windows[e],f=System.osWindowResizeMargin,b.x>c.x&&b.x<c.x+f&&b.y>c.y+f&&b.y<c.y+c.height-f?q=k.LEFT:b.x>c.x+c.width-f&&b.x<c.x+c.width&&b.y>c.y+f&&b.y<c.y+c.height-f?q=k.RIGHT:b.x>c.x+f&&b.x<c.x+c.width-f&&b.y>c.y&&b.y<c.y+f?q=k.TOP:b.x>c.x+f&&b.x<c.x+c.width-f&&b.y>c.y+c.height-f&&b.y<c.y+c.height?q=k.BOTTOM:b.x>c.x&&b.x<c.x+f&&b.y>c.y&&b.y<c.y+f?q=k.TOP_LEFT:b.x>c.x+c.width-f&&b.x<c.x+c.width&&b.y>c.y&&b.y<c.y+f?q=k.TOP_RIGHT:b.x>c.x&&b.x<c.x+f&&b.y>c.y+c.height-
f&&b.y<c.y+c.height?q=k.BOTTOM_LEFT:b.x>c.x+c.width-f&&b.x<c.x+c.width&&b.y>c.y+c.height-f&&b.y<c.y+c.height&&(q=k.BOTTOM_RIGHT),b.x>c.x&&b.x<c.x+c.width&&b.y>c.y&&b.y<c.y+c.height&&!(b.x>c.x+f&&b.x<c.x+c.width-f&&b.y>c.y+f&&b.y<c.y+c.height-f)&&(h=c,n=c.x,p=c.y,u=c.width,v=c.height)};window.onmousemove=function(b){if(y)if(null!=t)t.shown?(t.x=b.x-z,t.y=b.y-A):y=!1;else{if(q!=k.NONE)switch(q){case k.LEFT:b.x<n+u-System.osWindowMinimumWidth&&(h.x=b.x,h.width=n-b.x+u);break;case k.RIGHT:b.x>n+System.osWindowMinimumWidth&&
(h.width=b.x-n);break;case k.TOP:b.y<p+v-System.osWindowMinimumHeight&&(h.y=b.y,h.height=p-b.y+v);break;case k.BOTTOM:b.y>p+System.osWindowMinimumHeight&&(h.height=b.y-p);break;case k.TOP_LEFT:b.x<n+u-System.osWindowMinimumWidth&&(h.x=b.x,h.width=n-b.x+u);b.y<p+v-System.osWindowMinimumHeight&&(h.y=b.y,h.height=p-b.y+v);break;case k.TOP_RIGHT:b.x>n+System.osWindowMinimumWidth&&(h.width=b.x-n);b.y<p+v-System.osWindowMinimumHeight&&(h.y=b.y,h.height=p-b.y+v);break;case k.BOTTOM_LEFT:b.x<n+u-System.osWindowMinimumWidth&&
(h.x=b.x,h.width=n-b.x+u);b.y>p+System.osWindowMinimumHeight&&(h.height=b.y-p);break;case k.BOTTOM_RIGHT:b.x>n+System.osWindowMinimumWidth&&(h.width=b.x-n),b.y>p+System.osWindowMinimumHeight&&(h.height=b.y-p)}}else{for(var a=!1,d=[],g=0;g<windows.length;g++)b.x>windows[g].x&&b.x<windows[g].x+windows[g].width&&b.y>windows[g].y&&b.y<windows[g].y+windows[g].height&&d.push(g);d.pop();for(g=windows.length-1;0<=g;g--)if(-1==d.indexOf(g)){var c=windows[g],f=System.osWindowResizeMargin;b.x>c.x&&b.x<c.x+f&&
b.y>c.y+f&&b.y<c.y+c.height-f?(e.style.cursor="w-resize",a=!0):b.x>c.x+c.width-f&&b.x<c.x+c.width&&b.y>c.y+f&&b.y<c.y+c.height-f?(e.style.cursor="e-resize",a=!0):b.x>c.x+f&&b.x<c.x+c.width-f&&b.y>c.y&&b.y<c.y+f?(e.style.cursor="n-resize",a=!0):b.x>c.x+f&&b.x<c.x+c.width-f&&b.y>c.y+c.height-f&&b.y<c.y+c.height?(e.style.cursor="s-resize",a=!0):b.x>c.x&&b.x<c.x+f&&b.y>c.y&&b.y<c.y+f?(e.style.cursor="nw-resize",a=!0):b.x>c.x+c.width-f&&b.x<c.x+c.width&&b.y>c.y&&b.y<c.y+f?(e.style.cursor="ne-resize",a=
!0):b.x>c.x&&b.x<c.x+f&&b.y>c.y+c.height-f&&b.y<c.y+c.height?(e.style.cursor="sw-resize",a=!0):b.x>c.x+c.width-f&&b.x<c.x+c.width&&b.y>c.y+c.height-f&&b.y<c.y+c.height&&(e.style.cursor="se-resize",a=!0)}a||(e.style.cursor="default")}};window.onmouseup=function(b){null!=t&&y&&(t.x=b.x-z,t.y=b.y-A,t=null,A=z=0);q!=k.NONE&&(q=k.NONE);y=!1};window.onresize=function(b){e.width=window.innerWidth;e.height=window.innerHeight;d()};var k={LEFT:0,RIGHT:1,TOP:2,BOTTOM:3,TOP_LEFT:4,TOP_RIGHT:5,BOTTOM_LEFT:6,BOTTOM_RIGHT:7,
NONE:8}}var Application=function(a){a="undefined"==typeof a?Application.DEFAULT_RUN_COMMANDS:a;for(var d in a.commands){var e=a.commands[d];if("compile"==e.action)var m=new ApplicationCompiler(e.source,e.dest,function(a){m.setCode(a);var d=m.compile();$.ajax({type:"POST",url:"/user/set.php",data:{path:d.dest,content:d.code},success:function(a){d.callback(d.code)}})},e.callback);else"execute"==e.action&&(new ApplicationExecutor(e.source)).start()}};Application.DEFAULT_RUN_COMMANDS={commands:[{action:"execute"}]};
var ApplicationCompiler=function(a,d,e,m){this.appSource=a;this.isReady=!1;this.flags=[];this.dest=d;this.execAfter=m;$.ajax({type:"get",url:this.appSource,success:e})};ApplicationCompiler.prototype.compile=function(){if(this.isReady)return this.compiledCode="importScripts('"+System.scriptLangPath+"');\n"+this.appCode,{code:this.compiledCode,callback:this.execAfter,dest:this.dest};console.warn("Please wait to call compile() until source code has been loaded.")};
ApplicationCompiler.prototype.setCode=function(a){this.isReady=!0;this.appCode=a};ApplicationCompiler.prototype.setDest=function(a){this.dest=a};var ApplicationExecutor=function(a){this.path=a;this.windowIDs=[]};ApplicationExecutor.prototype.start=function(){console.log(this);this.internalWorker=new Worker("get.php?content_type=text/javascript&path="+this.path);this.internalWorker.thisEquiv=this;this.internalWorker.onmessage=ApplicationExecutor.handleRequest};
ApplicationExecutor.handleRequest=function(a){ApplicationExecutor.support.exe=this.thisEquiv;ApplicationExecutor.support[a.data.action](a.data.params)};
ApplicationExecutor.support={"System.println":function(a){console.log(a)},"System.Window.<init>":function(a){var d;windows.push(d=new Window(a.x,a.y,a.width,a.height,a.title,void 0,a.graphics.data));d.hide();this.exe.windowIDs.push({global:d.id,local:a.id})},"System.Window.show":function(a){var d=this["System.Window.getGlobalWindow"](a);this["System.Window.update"](a);d.show()},"System.Window.hide":function(a){var d=this["System.Window.getGlobalWindow"](a);this["System.Window.update"](a);d.hide()},
"System.Window.update":function(a){this["System.Window.getGlobalWindow"](a).update(a)},"System.Window.getGlobalID":function(a){for(var d=0;d<this.exe.windowIDs.length;d++){var e=this.exe.windowIDs[d];if(e.local==a.id)return e.global}},"System.Window.getGlobalWindow":function(a){return windows.findID(this["System.Window.getGlobalID"](a))},exe:null};function o(a,d){return"undefined"==typeof a?"function"==typeof d?d():d:a}Array.prototype.swap=function(a,d){var e=this[a];this[a]=this[d];this[d]=e;return this};
Array.prototype.remove=function(a){delete this[a];a=[];for(var d=0;d<this.length;d++)"undefined"!=typeof this[d]&&a.push(this[d]);return a};Array.prototype.findID=function(a){for(var d=0;d<this.length;d++)if(this[d].id==a)return this[d]};CanvasRenderingContext2D.prototype.clear=CanvasRenderingContext2D.prototype.clear||function(a){a&&(this.save(),this.setTransform(1,0,0,1,0,0));this.clearRect(0,0,this.canvas.width,this.canvas.height);a&&this.restore()};
function getWidthIndex(a){var d=[],e="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890!@#$%^&*()`~-=_+[]{}|\"';:/?>.<, ".split(""),m=document.createElement("canvas").getContext("2d");m.font=a;for(a=0;a<e.length;a++){var r=e[a];d.push([r,m.measureText(r).width])}return d}Image.getIcon=function(a){var d=new Image(System.osWindowIconWidth,System.osWindowIconHeight);d.src=a;return d};
String.prototype.toHex=function(){var a,d,e="";for(d=0;d<this.length;d++)a=this.charCodeAt(d).toString(16),e+=("000"+a).slice(-4);return e};String.prototype.fromHex=function(){var a,d=this.match(/.{1,4}/g)||[],e="";for(a=0;a<d.length;a++)e+=String.fromCharCode(parseInt(d[a],16));return e};function defined(a){return!("undefined"==typeof a||null==a)}
function Window(a,d,e,m,r,g,x){this.update(a,d,e,m,r,g,x);this.id=Window.nextID;this.preHide={};this.shown=!0;this.event={mousedown:function(){},mouseup:function(){},mousemove:function(){}};windows.push(this);Window.nextID++}Window.prototype.show=function(){this.x=this.preHide.x;this.y=this.preHide.y;this.preHide={};this.shown=!0};
Window.prototype.hide=function(){this.preHide={x:this.x,y:this.y};this.x=-this.width-System.osWindowBorderWidth;this.y=-this.height-System.osWindowBorderWidth;this.shown=!1};
Window.prototype.update=function(a,d,e,m,r,g,x){"object"==typeof a?(this.title=a.title,this.icon="undefined"==typeof a.icon?Image.getIcon(System.osApplicationIcon):a.icon,this.gdata="undefined"==typeof a.graphics.data?Defaults.windowGData:a.graphics.data):(this.x=a,this.y=d,this.width=e,this.height=m,this.title=r,this.icon="undefined"==typeof g?Image.getIcon(System.osApplicationIcon):g,this.gdata="undefined"==typeof x?Defaults.windowGData:x)};
Window.prototype.addEventListener=function(a,d){this.event[a]=d};Window.nextID=0;
